### ISSUE TITLE
Uncaught TypeError: Cannot read property 'play' of undefined. in Example

### ISSUE THREAD

**Issue by jasan-s** [videojs/videojs-vimeo#102]
`
TypeError: Cannot read property 'play' of undefined at K (http://127.0.0.1:8887/lib/video.js:48:118) at d.t.play (http://127.0.0.1:8887/lib/video.js:48:449) at d.u.Ta.p (http://127.0.0.1:8887/lib/video.js:83:210) at HTMLDivElement.e (http://127.0.0.1:8887/lib/video.js:10:334) at HTMLDivElement.e.U.e.U (http://127.0.0.1:8887/lib/video.js:4:338)
length
:
1
__proto__
:
Array(0)
`

**Comment by gkatsev** [comment]
I dont think this will be a problem anyway if you're using a new-enough videojs and latest master.
