### ISSUE TITLE
playbackRate issue!

### ISSUE THREAD

**Issue by vbetivu** [videojs/videojs-vimeo#145]
hi, i am using videojs together with vimeo plugin, when i try to set/change playbackRate i get this issue in my console 
![image](https://user-images.githubusercontent.com/37940672/46954937-6d2ce580-d09a-11e8-9611-150e53c69811.png)
any help will be really appreciated.
thanks!

**Comment by balindenberg** [comment]
Hi @v1lad, did you ever end up fixing this? Experiencing the same currently.
