### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Magiweb** [videojs/videojs-vimeo#65]
@eXon sorry I realised I commented on a closed issue, so I created this one. 

I'm also having a lot of problems with this plugin not working; I'm using VideoJS version 5.7. 

Your Youtube plugin works flawlessly, but using the exact same code to instantiate a vjs/vimeo player just breaks constantly. It looks like maybe some kind of a race issue? I'm getting this error:

`TypeError: a is undefined - video.min.js (line 22, col 3904)`
`TypeError: a is undefined video.min.js (line 22, col 3981)`

Sometimes I get lucky and it loads, but most times it doesn't, especially if I dynamically create a <video> tag using javascript and try to attach videojs/vimeo to that.

Would you be willing to help us resolve this? We're desperate to get this working by next Friday...

**Comment by Magiweb** [comment]
@hendrathings I notice that you made the update to support version 5 - maybe you can shed some light on this? To replicate, initialise the script as normal, then dispose the player, and delete the <video> DOM element. Then create a new <video> dom element and try creating the videojs object using the videojs("id", {...}); method. I can shoot a video to show you how to replicate the problem if it helps, or maybe provide sample code if necessary. 

I'd be deeply grateful for any help anyone can offer to resolve this.

**Comment by hendrathings** [comment]
@Magiweb Have you use the new version `src/Vimeo.js` ?
and use 
```
<video
    id="vid1"
    class="video-js vjs-default-skin"
    controls
    autoplay
    width="640" height="264"
    data-setup='{ "techOrder": ["vimeo"], "sources": [{ "type": "video/vimeo", "src": "https://vimeo.com/153979733"}] }'
  >
  </video>
```

**Comment by Magiweb** [comment]
@hendrathings thanks for replying. We're not instantiating the video like that - we're doing it via the videojs() function, like this: 

`videojs("preview", {
                        techOrder: [ 'vimeo' ],
                        controls : true,
                        sources  : [
                            {
                                type: "video/vimeo",
                                src : elm.attr('data-video-url')
                            }
                        ]
                    }, function() {
                        //Success
                    });`

Since we have a list of Vimeo videos we show, they can click on an item and we pop up a modal with the videojs video in there and play the video. So we dispose() the videojs object first, then use above code to instantiate it again with a new source and a dom element we create in jQuery. 

We're also using it in a custom "page builder" where we drag and drop the <video> element into a block of HTML, and that breaks too, so it seems like it's something to do with dynamically created <video> tags maybe? It works perfectly with eXon's Youtube plugin, but for some reason not with the Vimeo plugin. 

Here's a video I shot for you which shows the problem: http://screencast.com/t/MhtNC9AuIvr

**Comment by Magiweb** [comment]
I tried a different approach for the find videos (which wouldn't solve the problem with the builder, but at least I was hoping it would in the Find Videos section of my app. Instead of rebuilding the DOM element, I simply tried switching out the source and triggering a "loadstart" on VideoJS: 

```
window.player.src([
                        { type: "video/vimeo", src: elm.attr('data-video-url') }
                    ]).currentTime(0).trigger('loadstart');
```
Doing it this way, the video player doesn't break, but the source is not replaced with the new one, so it only ever plays the first source defined during instantiation of the Videojs object.

**Comment by Magiweb** [comment]
@hendrathings is there any chance this can get resolved? And ideas on what the issue is?

**Comment by hendrathings** [comment]
please wait, I still figure out :)

**Comment by Magiweb** [comment]
@hendrathings and @eXon it looks like some work's been pushed into this, but I'm not sure which update to use? There's a pending pull request, but there's also been a version update thereafter; which one is the fix? Does the master branch have the fix, or do I try hendrathings's local branch?

I appreciate the work you're doing with this guys - thanks!

**Comment by Magiweb** [comment]
@hendrathings your bug-fix version works WAY better, thanks! 

The only thing that's still not working on that version so far for me is the ability to change source on-the-fly, so I can't "string" more than 1 video together like a playlist. I have to dispose() and re-create the <video> DOM element and the videoJS object. Still something I hope you will fix that at some point.

**Comment by gkatsev** [comment]
Latest master works now.
