### ISSUE TITLE
npm ERR! missing script: build

### ISSUE THREAD

**Issue by raymestalez** [videojs/videojs-vimeo#69]
Hi! When I'm running npm run build I'm getting an error:

`npm ERR! missing script: build`

Can you help me out?

Or maybe it would make sense to just compile vimeo.min.js and make it available for download, so that people could just download it?

**Comment by gkatsev** [comment]
I think that the build script is unfortunately missing from the package.json. Probably can be copied over from videojs-youtube.

**Comment by jrglass** [comment]
Having the same issue.
Tried to use package.jason from the videojs-youtube directory and it failed.

Says this fails on my system: 
`mkdirp dist && cp src/Youtube.js dist/Youtube.js && uglifyjs src/Youtube.js -o dist/Youtube.min.js`

Any way to get the correct build file for the Vimeo plugin so it works correctly?
Do I actually need to build it or can I roll with Vimeo.js that's in src folder?

**Comment by gkatsev** [comment]
The build should be fixed in master now.
