### ISSUE TITLE
Video displayed outside of player frame

### ISSUE THREAD

**Issue by samueldjack** [videojs/videojs-vimeo#70]
I've just discovered an interesting bug: if I set fluid: true in videojs data-setup options, the Vimeo video displays outside of the videojs player frame, like this:

![image](https://cloud.githubusercontent.com/assets/837684/13778393/617b13cc-eaad-11e5-9477-07d3f2b25885.png)

This doesn't happen with YouTube videos when fluid: true is set.

**Comment by albi** [comment]
Had the same issue, made a hotfix with CSS:

`.vimeoFrame {
	position: absolute !important;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
}
`

**Comment by samueldjack** [comment]
That fixed it. Thanks!

**Comment by gino8080** [comment]
@albi Great!!

this css should merged so I think this can be closed!

**Comment by gkatsev** [comment]
This shouldn't be a problem in master now. Unfortunately, the official vimeo API doesn't provide a way to hide their controls and use the videojs controls, so, we're stuck with the vimeo controls now.
