### ISSUE TITLE
Can't get the plugin it to work, Youtube works fine, but not Vimeo…

### ISSUE THREAD

**Issue by albi** [videojs/videojs-vimeo#71]
Hi,

got a problem with the vimeo plugin for videojs. The vimeo videos won't load. I think this is not an issue with my code, as I used a stripped down example from videojs and added the plugins as it was explained in the readme.

http://alexanderalbrecht.ch/video-js/index.html Youtube videos work as intended
http://alexanderalbrecht.ch/video-js/index-vimeo.html Vimeo videos won't load

kind regards
alex

**Comment by Joeao** [comment]
Which version of VideoJS are you using?

**Comment by albi** [comment]
Version 5.8

But there is another problem with the vimeo plugin too, maybe this is related to https://github.com/eXon/videojs-vimeo/issues/70

**Comment by albi** [comment]
Still having problems with VideoJS 5.8.8

**Comment by mihayee** [comment]
Hi I came across the same problem after installed the latest version of video.js and vimeo.js.

**Comment by jrglass** [comment]
Having the same issue. Has this been resolved or is there a fix?

I'm also seeing a few errors in the console:

VIDEOJS: ERROR: The "Vimeo" tech is undefined. Skipped browser support check for that tech
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. e {code: 4, message: "No compatible source was found for this media."}

I'm just using the Vimeo.js file as I couldn't run npm build to get the min file.

Any ideas?

**Comment by Migueeeeel** [comment]
Hi. Just came across the same problem, works great on local windows 10 machine, but in the server (unix) doesn't work, gives the same error as jrglass.

**Comment by gkatsev** [comment]
Should be working in master now. A new release will be coming shortly.
