### ISSUE TITLE
errors at re-initializing vimeo videos after dispose()

### ISSUE THREAD

**Issue by craigstar** [videojs/videojs-vimeo#73]
With dynamical creating, disposing video elements, it works for the first time. but it throw me an error at the second initialization. `Uncaught TypeError: Cannot read property 'vdata1458668645722' of undefined` at `function getElData(el) {` in video.js. 

```
$('#video-btn-vimeo').click ->
      video = '<video id="video-player" class="video-js vjs-default-skin vjs-big-play-centered"></video>'
      $(video).insertAfter $('.video-placeholder')

      $('#video-player').width('100%')
      $('#video-player').css({
        'min-height': $('.video-placeholder').height(),
      })
      videojs 'video-player',
        controls: true,
        techOrder: ["vimeo"],
        sources: [{
          type: "video/vimeo",
          src: $('#video-btn-vimeo').attr('data-video'),
        }],
```

```
$('#video-close-btn').click ->
      videojs('video-player').dispose()
```

First use the code above to create an video, then dispose(), then create again. error comes. 
 `video-youtube` works well. No luck for vimeo

**Comment by pikilon** [comment]
+1

**Comment by craigstar** [comment]
@pikilon unfortunately, I haven't found any solution. Just stopped using `videojs-vimeo`

**Comment by Magiweb** [comment]
@craigstar I found that if I re-created the <video> DOM element and then instantiated VideoJS on that element it would work again.

**Comment by craigstar** [comment]
Thank you! @Magiweb, `https://github.com/hendrathings/videojs-vimeo/tree/bug-api` has fixed this bug. However, I can not implement `videojs-vimeo` cause its not working on mobile devices. `https://github.com/eXon/videojs-vimeo/issues/72`

**Comment by craigstar** [comment]
@pikilon you could try this ` https://github.com/hendrathings/videojs-vimeo/tree/bug-api`

**Comment by pikilon** [comment]
Sorry but din't work out for me.
I recreated the dom ( I make a dispose, later a empty() or html("") the parent tag), set the variable to null and re-add the html video tag with the same id to later on videojs("theID", params, callback) and didn't work out.
"TypeError: Cannot read property 'vdata1458847063210' of undefined"

**Comment by twig** [comment]
Also having issues with dispose() not working correctly

**Comment by pietrovismara** [comment]
+1
This is a serious problem

**Comment by monstrfolk** [comment]
Spent all night trying different forks for this issue. Found a fork that work and had the CSS strange. I forked and fixed the CSS. 

https://github.com/rjgb/videojs-vimeo

**Comment by twig** [comment]
Found a solution which seems to be working for us.

The cause of this bug is dispose() actually removes the mount element of videojs. So when we try to re-initialise videojs/vimeo, it fails.

Simply recreating the element/mount point will fix this issue.

**Comment by Tresky** [comment]
@twig How do you mean when you say recreate the mount point?

**Comment by twig** [comment]
For example, you use `<div id="x"/>` as your mount point for VJS, `var vjs = $('#x').videojs();`.

When it's disposed via `vjs.dispose();`, the div is actually removed as well. You need to create a NEW `<div id="x"/>` in the same place before calling `$('#x').videojs()` again.

**Comment by mrtag23** [comment]
@craigstar @Magiweb thanks guys for posting the solution! saved me a lot of time, I wonder it autoplay stopped working only for me or it is a effect of patched code?

**Comment by buzzyboy** [comment]
I tried the suggested solution @twig provided. But that doesn't seem to be working for me.

**Comment by gkatsev** [comment]
Shouldn't be a problem in master anymore.
