### ISSUE TITLE
Vimeo.js: Cannot read property 'getJSON' of undefined

### ISSUE THREAD

**Issue by nowned** [videojs/videojs-vimeo#74]
Getting this error when trying to use a Vimeo embed
`Vimeo.js:94 Uncaught TypeError: Cannot read property 'getJSON' of undefined`

Code is embedded like this
`<div data-setup="{ "techOrder": ["vimeo"], "sources": [{ "type": "video/vimeo", "src": "https://vimeo.com/153836040"}] }" class="video-js vjs-sublime-skin vjs-paused project-video-dimensions" id="project-video"></div>`

Here are my versions.
"videojs-vimeo": "^2.0.0",
"video.js": "videojs#^5.8.5",

**Comment by IJsLauw** [comment]
Same problem here... seams the url has changed or is different for hidden video's?

**Comment by gor181** [comment]
It depends on global jQuery...
http://prntscr.com/axsl57

Adding jQuery as global dep will solve this.
It should support jQuery as module as it's doing now for video.js

**Comment by janxalot** [comment]
How do you suggest adding jQuery as a global dep? 

I have the original video.js working, however I am receiving the same error message as original post.

**Comment by janxalot** [comment]
I have jQuery added as a global dependency for a project I am working on and I am still encountering this error message. 

The default video.js package works fine, just trying to use the vimeo add-on returns the error.

Any ideas?

**Comment by joelstransky** [comment]
This is a big issue when using no-conflict jquery. 
You should probably use a non-jquery ajax request. http://youmightnotneedjquery.com/#request
In the mean time, anyone have an idea how to fix this?

**Comment by hiraylo** [comment]
A quick fix would be to replace the $with jQuery so that it reads like jQuery.getJSON

**Comment by joelstransky** [comment]
That's an edit to source which makes upgrading impossible. The authors
should just fix it.

**Comment by janxalot** [comment]
Agree 100%!

**Comment by gkatsev** [comment]
Should be fixed in master now.
