### ISSUE TITLE
Change SRC fail

### ISSUE THREAD

**Issue by pikilon** [videojs/videojs-vimeo#75]
Because reinitialize fails I tried to reuse a different players for each source (youtube, vimeo...)

But I change myplayer.src("new video link") and it simply ignore it.

Am I doing something the wrong way?

**Comment by Magiweb** [comment]
@pikilon this is definitely a bug with this plugin - dispose doesn't do a proper cleanup. https://github.com/eXon/videojs-vimeo/issues/73

**Comment by gino8080** [comment]
+1 for this

**Comment by zackurben** [comment]
@pikilon @Magiweb @gino8080 You can use my version of the plugin: https://github.com/zackurben/videojs-vimeo

I fixed this issue, and I've been updating my PR: https://github.com/eXon/videojs-vimeo/pull/76
but it doesn't look like it'll get pulled in (due to inactivity).

**Comment by gino8080** [comment]
@zackurben how to use the change video source?

thank you!

**Comment by gino8080** [comment]
ok got it in the example ! :)

is it possibile to listen for the "is ready after changed src" to make it autoplay?

thank you very much!

**Comment by zackurben** [comment]
@gino8080 sorry for the late reply. After you change the src, you should be able to start playing it:

```javascript
var video = videojs(..);
video.src(<a new video url>);
video.play();
```

or, if you have the autoplay option enabled, it should autoplay when the src is changed: https://github.com/zackurben/videojs-vimeo/blob/master/src/Vimeo.js#L277

let me know if you get it working.

**Comment by gkatsev** [comment]
This should be fixed in master now, though, there's a bug right now where if you switch away from vimeo tech, the videojs controls may still be hidden.
