### ISSUE TITLE
Why vimeo no autoplay?! 

### ISSUE THREAD

**Issue by floodedcodeboy** [videojs/videojs-vimeo#77]
Have tried the example with another vimeo video and the video does not autoplay. 👎

**Comment by gino8080** [comment]
same here :(

**Comment by asalisbury** [comment]
I haven't taken the time yet to root out the cause, but I noticed that `muted` attribute gets ignored as well. You could temporarily implement autoplay (and muted) like this:

```javascript
  var player, isMuted, autoplay;
  player = videojs('my-vid');
  isMuted = $('#my-vid').attr('muted') || false;
  autoplay = $('#my-vid').attr('autoplay');
  player.muted(isMuted).ready(function () {
    if (autoplay) {
      this.play();
    }
  });
```

**Comment by gkatsev** [comment]
This works in master now. Though, it doesn't yet accept the videojs player options for that. It should.

**Comment by gkatsev** [comment]
Nope, looks like that does work.
