### ISSUE TITLE
Vimeo Parameters

### ISSUE THREAD

**Issue by prock13** [videojs/videojs-vimeo#81]
The Vimeo Parameters link is not working: https://developers.google.com/vimeo/player_parameters?hl=en#Parameters

What are the options for ytcontrols?  

Is there another link that has this info?

**Comment by arnoldsandoval** [comment]
+1

**Comment by samhibberd** [comment]
+1

**Comment by gkatsev** [comment]
ytControls are strictly for youtube.
Master has fixed various vimeo options.

**Comment by gkatsev** [comment]
Here are the various options available: https://github.com/vimeo/player.js#embed-options
