### ISSUE TITLE
Not a issue But suggestion for Vimeo with Videojs 5+

### ISSUE THREAD

**Issue by onigetoc** [videojs/videojs-vimeo#82]
The Vimeo plugin do not work with the latest Videojs 5+. 
It would be great to do a Vimeo plugin based on your Youtube plugin.
There's a api for Vimeo
[https://developer.vimeo.com/player/js-api](url)
Here a way to remove with css all Vimeo Control.
[http://www.cssplay.co.uk/menu/cssplay-vimeo-hide-control-bar.html](url)
Vimeo API example.
[https://github.com/vimeo/player-api](url)

**Comment by gkatsev** [comment]
We've updated to use the newest official vimeo API. Thanks.

**Comment by onigetoc** [comment]
Hi, i think you should change de Vimeo URL https to http.
Error:
```
Refused to load the script
because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'
```

**Comment by gkatsev** [comment]
We're using the native API and not doing anything like that ourselves. Injection of the CSS in the js might be causing CSP issues but otherwise, I would say it's something that vimeo is doing.

**Comment by onigetoc** [comment]
There's a url inside the js file pointing to vimeo api with https
it mean that if you are on a non https server the plugin will not work.
I tryed it online and it give this error. 
I tryed it on my local server and i have no error.

The only strange thing it's it load the Vimeo control bar.
but you may have changed the way to use it and i didn't read the vimeo.js doc yet.

**Comment by gkatsev** [comment]
Yes, unfortunately, vimeo doesn't provide a way to hide their control bar.

As for an http url, I'm not seeing any HTTP urls in the dist file.

**Comment by onigetoc** [comment]
It may be tricky but look here.
http://www.cssplay.co.uk/menu/cssplay-vimeo-hide-control-bar.html

**Comment by gkatsev** [comment]
Yeah, I've seen that. I'm not sure we want to do that and it may be against vimeos TOS.
