### ISSUE TITLE
Works but showing a 404 in console

### ISSUE THREAD

**Issue by chrisbaswell** [videojs/videojs-vimeo#83]
![screen shot 2016-06-24 at 11 41 53 am](https://cloud.githubusercontent.com/assets/801686/16344176/efa9058a-3a00-11e6-8ec1-3a6426232d10.png)

Not really sure what's happening.  The video loads correctly but I was getting the same results as #70.  Adding the CSS works but I think the problem may lie in the 404 error I'm receiving.  Maybe it's trying to load the video twice and taking up additional space.  Not sure at all.  Just thought I'd share the error :)

**Comment by gkatsev** [comment]
I don't think this will be happening anymore in master.
