### ISSUE TITLE
Example fails after build

### ISSUE THREAD

**Issue by rw3iss** [videojs/videojs-vimeo#84]
Have all the files being included properly, network tab shows they are downloaded correctly. 
Initialization throws these errors:

Vimeo.js:39 Uncaught TypeError: videojs.getComponent is not a function(anonymous function) @ Vimeo.js:39(anonymous function) @ Vimeo.js:26(anonymous function) @ Vimeo.js:28
3video.js:59 Uncaught TypeError: Cannot read property 'S' of undefined

I've tried to use both the 5.0 and 4.0 version of the video.js library.

**Comment by Malmoc** [comment]
Running into the exact same issues. Can't wait for a fix.

**Comment by glpunk** [comment]
Same Issue

**Comment by gkatsev** [comment]
If you're using Video.js 5 and master, it should be working now.
