### ISSUE TITLE
Conflict with Vimeo HTML5 Player API - Migration Attempt  

### ISSUE THREAD

**Issue by justtobeok** [videojs/videojs-vimeo#86]
Hey,
I am trying to migrate this plugin to the new Vimeo Api. 
https://github.com/vimeo/player.js

The first Part does not seem to be a problem, I am able to change all the Events an Methods, rename the Vimeo Constructor and throw out the Froogaloop API. 

For some reason as I change
`self.vimeo = $f(self.iframe);`  to 
`self.vimeo = new Vimeo.Player(self.iframe);` 
I get an error "Cannot read property 'Player' of undefined". I am sure the new Vimeo Player API is loaded before the script, but somehow seems to be out of scope. I am not a JS-Pro I have to admit.

Has anybody ever done this or any suggestion? 
Have you considered migrating the Plugin to the new Player API?

Thank you

**Comment by jeanmichelcote** [comment]
How is the migration going? Still working on it?

**Comment by justtobeok** [comment]
I fiddled around quite a bit, but with time running out I decided to take one step back, throw out the whole video.js part and then went with plyr https://github.com/Selz/plyr

**Comment by jeanmichelcote** [comment]
I just checked it out. The thing is that Plyr uses the old Froogaloop API for dealing with Vimeo. Same as Video.js.

I believe I'll go ahead and directly use the new vimeo API on a vimeo pro account...

**Comment by justtobeok** [comment]
No it does not, when you look at the code, in line 155 plyr loads the new API:
https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L155

and creates the player object with the new syntax in line 1749:
https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L1749

even referring to the git of the new API on line before in the comment....

**Comment by gkatsev** [comment]
Master is now using the official vimeo player API.
