### ISSUE TITLE
About the old version filename and main file

### ISSUE THREAD

**Issue by x09326** [videojs/videojs-vimeo#94]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).

First I am not sure which files should be added.
Is the file in `src` needed?
And second I want to confirm the file `Vimeo.js` in the latest version which is same as the file `media.vimeo.js` in v1.0.2 or not.
Please help me solve it, thanks.
https://github.com/cdnjs/cdnjs/pull/9565

**Comment by gkatsev** [comment]
Hey, so, we're in the process of updating this plugin to use the official vimeo API. It'll also be published to npm and be available in the `dist/videojs-vimeo.js` file from that package. So, you could probably update it to use that format and update via npm updates. Some other videojs plugins are already working with that, I think, even video.js itself works that way now.

**Comment by extend1994** [comment]
Hi @gkatsev @eXon @hendrathings
Sorry to bother you.
I am the current CDNJS member in charge of adding this lib. I tried to use `npm run build` to get `dist/Vimeo.min.js`, but nothing appeared. Is there any other way to get the file same as `dist/Vimeo.min.js`? Maybe minify `src/Vimeo.js` in v2.0.0 ~ v2.0.2 and `src/media.vimeo.js` in v1.0.2? Thank you!
