### ISSUE TITLE
Hide Vimeo Controls

### ISSUE THREAD

**Issue by samhibberd** [videojs/videojs-vimeo#97]
Can you hide the Vimeo controls and just use the VideoJS controls? The ytControls parameter does not seem to work.

**Comment by gkatsev** [comment]
ytControls is for the youtube tech, accidentally got pulled in.
Unfortunately, vimeo doesn't provide a way to hide their controls and just use the videojs controls.

**Comment by emilz0r** [comment]
So to clarify: this plugin is meant to display the vimeo player gui for controlling the video, and not the videojs player gui? Is there any plans to make it use the videojs gui?
