### ISSUE TITLE
Broken for single page applications

### ISSUE THREAD

**Issue by charlesoconor** [videojs/videojs-vimeo#98]
There must be something wrong with the start up process. It can load as many videos as you want if it does it at the same time.   If you try to load another vimeo embed after the first round has finished it crashes every time. 

![screen shot 2017-01-19 at 4 50 58 pm](https://cloud.githubusercontent.com/assets/8228660/22126880/8f895112-de67-11e6-9f40-5d0bc3018379.png)

**Comment by gkatsev** [comment]
I think it's been fixed in master.
